 <div class="main-content-inner">
	<div class="breadcrumbs ace-save-state" id="breadcrumbs">
		<ul class="breadcrumb">
			<li>
				<i class="ace-icon fa fa-home home-icon"></i>
				<a href=""></a>
			</li>

		    <li ><a href="{:url('index')}"><?php echo $table?>列表</a></li>
			<li class="active">添加</li>
		</ul>
	</div>

	<div class="page-content">
		<div class="panel-body">
			<form id="myform" method="post" class="form-horizontal" action="{:url('add')}">
			
			 <?php foreach($columnsList as $column){?>	 

					<div class="form-group" <?php if($column['display']!=1){?>style="display: none"<?php }?> >
						<label for="input-title"  class="col-sm-2 control-label"><?php echo $column['text']?></label>
						<div class="col-sm-7">
							 <input type="text" name="<?php echo $column['name']?>" value="{$data-><?php echo $column['name']?>}" class="form-control" >
						</div>
					</div>
				<?php }?>

			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-7">
					<button type="submit" class="btn btn-primary">保存</button>
				</div>
			</div>

			</form>
		</div>
	</div>
</div>

<script>
 
$(function(){
    $(".form-horizontal").bootstrapValidator({
        message: '您填入的值不合法',
        fields:{
 <?php foreach($columnsList as $column){?>	
 	 <?php if($column['required']==1){?>
			<?php echo $column['name']?>: {
                message: '<?php echo $column['text']?>',
                validators: {
                    notEmpty: {
                        message: '<?php echo $column['text']?>不能为空'
                    },
                }
            }, 
     <?php }?>      
 <?php }?>       
        }
    });
 
	});
 </script> 